---
title: "Gomperts Truncated "
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{gompertz-truncated}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(gompertztrunc)
library(tictoc)
```


In this vignette, we will demonstrate how to use the functions in the `gompertztrunc` package to estimate hazard ratios for doubly-truncated data. 


We will use the built-in CenSoc example dataset. 

```{r}
censoc_example
```

```{r}
tic()
gompertz_mle(death_age ~ educ_yrs, lower = 1975, upper = 2005, data = censoc_example)
toc()
```

```{r}
tic()
gompertz_mle(death_age ~ ownhome, lower = 1975, upper = 2005, data = censoc_example)
toc()
```

```{r}
tic()
model_results <- gompertz_mle(death_age ~ educ_yrs + ownhome + urban, lower = 1975, upper = 2005, data = censoc_example)
toc()
```

```{r}
censoc_example <- censoc_example %>% 
  mutate(educ_yrs_factor = as.factor(educ_yrs))

tic()
model_results <- gompertz_mle(death_age ~ educ_yrs_factor, lower = 1975, upper = 2005, data = censoc_example)
toc()
```


```{r}
mle_results <- convert_hazards_to_e65(model_results) %>% 
   mutate(parameter = prefix_strip(parameter, "educ_yrs_factor_")) %>% 
  mutate(parameter = as.numeric(parameter)) %>% 
  mutate(method = "Gompertz MLE")

mle_results %>% 
  ggplot(aes(x = parameter, y = e65, ymin = e65_lower, ymax = e65_upper)) + 
  geom_pointrange(position = position_dodge(width = 0.2)) + 
  cowplot::theme_cowplot() + 
  ggsci::scale_color_lancet() + 
  labs(x = "Years of Schooling",
       y = "Estimate",
       title = "Education and Life Expectancy at Age 65") + 
  theme(legend.position = "bottom")
```


